name: collect checklists

on:
  workflow_dispatch:
  schedule:
    - cron: '47 0 * * *'

jobs:
  collect_checklists:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
          
      - name: Set up dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run script to collect recent checklists
        run: python 01_collect_data/collect_checklists.py
        env:
          EBIRD_PW: ${{ secrets.EBIRD_PW }}
          EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
        
      - name: Commit and push new checklists, if there are any
        run: |
          git config --global user.name 'oatnewguo'
          git config --global user.email 'oatnewguo@gmail.com'
          git add .
          git commit -m 'Automated checklist update' || echo 'No changes to commit'
          git push
